### ISSUE TITLE
Would like to shrink motion-based objectness thesis repo so it can be forked

### ISSUE THREAD

**Issue by bentito** [wrongu/thesis#1]
Hi,
I'm working in Granger Lab, Rick has asked me to look more at your objectness work. I'd like to properly fork it to a GitHub account paid for by the lab. But with the training video directories, it's way over the size that GitHub will allow to be forked -- needs to be <1GB they tell me. I think it's important to have the training videos as part of the project, but maybe they could go in Google Drive and be replaced in the repo by a link to the directory?

If you want to leave your repo as is, I understand, but I'll probably go a route of cloning it, paring it down as mentioned above and creating a stand-alone repo. I'd rather be able to fork in GitHub (can't as is), clone, and add your repo as the remote upstream, This would allow me to be able to track and merge your changes and send you pull requests as I accomplish useful stuff.

-brett

**Comment by wrongu** [comment]
The reason it was such a big repo was that, to save hours of computation time, I had it save the results of every optical-flow calculation it did. I have removed all of these files (which will be automatically recreated the first time it is run), and it is down to closer to 1GB, though still slightly over.

If necessary, I can move the training data (999MB) to a public dropbox folder.

**Comment by bentito** [comment]
Ok, great, I'll try forking as-is and see if GitHub lets me this time.

**Comment by wrongu** [comment]
well... it's still in the process of uploading the latest commit

**Comment by bentito** [comment]
Okay, please post when the commit finishes successfully, I'll try a fork again.
